name: 'proyecto_combustibles'
version: '1.0'
profile: 'default'
config-version: 2

model-paths: ["models"]

models:
  proyecto_combustibles:
    staging:
      +materialized: table
    marts:
      +materialized: table
